// ============================================================
// CURRENCIES CONSTANTS
// ============================================================
// This file contains the master list of all supported currencies.
// Each entry has:
//   code   - ISO 4217 currency code (e.g., 'USD', 'LKR', 'AED')
//   name   - Human-readable name shown in the UI
//   symbol - Symbol used when displaying amounts (e.g., '$', 'LKR')
// ============================================================

export const ALL_CURRENCIES = [
  { code: 'USD', name: 'United States Dollar (USD)', symbol: '$' },
  { code: 'GBP', name: 'British Pound (GBP)', symbol: '£' },
  { code: 'EUR', name: 'Euro (EUR)', symbol: '€' },
  { code: 'JPY', name: 'Japanese Yen (JPY)', symbol: '¥' },
  { code: 'CAD', name: 'Canadian Dollar (CAD)', symbol: 'C$' },
  { code: 'AUD', name: 'Australian Dollar (AUD)', symbol: 'A$' },
  { code: 'AED', name: 'United Arab Emirates Dirham (AED)', symbol: 'AED' },
  { code: 'LKR', name: 'Sri Lankan Rupee (LKR)', symbol: 'LKR' },
  { code: 'INR', name: 'Indian Rupee (INR)', symbol: '₹' },
  { code: 'CHF', name: 'Swiss Franc (CHF)', symbol: 'CHF' },
  { code: 'CNY', name: 'Chinese Yuan (CNY)', symbol: '¥' },
  { code: 'SGD', name: 'Singapore Dollar (SGD)', symbol: 'S$' },
  { code: 'NZD', name: 'New Zealand Dollar (NZD)', symbol: 'NZ$' },
  { code: 'HKD', name: 'Hong Kong Dollar (HKD)', symbol: 'HK$' },
  { code: 'ZAR', name: 'South African Rand (ZAR)', symbol: 'R' },
  { code: 'SEK', name: 'Swedish Krona (SEK)', symbol: 'kr' },
  { code: 'NOK', name: 'Norwegian Krone (NOK)', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone (DKK)', symbol: 'kr' },
  { code: 'RUB', name: 'Russian Ruble (RUB)', symbol: '₽' },
  { code: 'KRW', name: 'South Korean Won (KRW)', symbol: '₩' },
  { code: 'TRY', name: 'Turkish Lira (TRY)', symbol: '₺' },
  { code: 'BRL', name: 'Brazilian Real (BRL)', symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso (MXN)', symbol: '$' },
  { code: 'SAR', name: 'Saudi Riyal (SAR)', symbol: 'SR' },
  { code: 'QAR', name: 'Qatari Riyal (QAR)', symbol: 'QR' },
  { code: 'OMR', name: 'Omani Rial (OMR)', symbol: 'RO' },
  { code: 'BHD', name: 'Bahraini Dinar (BHD)', symbol: 'BD' },
  { code: 'KWD', name: 'Kuwaiti Dinar (KWD)', symbol: 'KD' },
  { code: 'MYR', name: 'Malaysian Ringgit (MYR)', symbol: 'RM' },
  { code: 'IDR', name: 'Indonesian Rupiah (IDR)', symbol: 'Rp' },
  { code: 'PHP', name: 'Philippine Peso (PHP)', symbol: '₱' },
  { code: 'THB', name: 'Thai Baht (THB)', symbol: '฿' },
  { code: 'VND', name: 'Vietnamese Dong (VND)', symbol: '₫' },
  { code: 'PKR', name: 'Pakistani Rupee (PKR)', symbol: 'Rs' },
  { code: 'BDT', name: 'Bangladeshi Taka (BDT)', symbol: '৳' },
  { code: 'NPR', name: 'Nepalese Rupee (NPR)', symbol: 'Rs' },
  { code: 'EGP', name: 'Egyptian Pound (EGP)', symbol: 'E£' },
  { code: 'ILS', name: 'Israeli New Shekel (ILS)', symbol: '₪' },
  { code: 'PLN', name: 'Polish Zloty (PLN)', symbol: 'zł' },
  { code: 'HUF', name: 'Hungarian Forint (HUF)', symbol: 'Ft' },
  { code: 'CZK', name: 'Czech Koruna (CZK)', symbol: 'Kč' },
  { code: 'RON', name: 'Romanian Leu (RON)', symbol: 'lei' },
  { code: 'CLP', name: 'Chilean Peso (CLP)', symbol: '$' },
  { code: 'COP', name: 'Colombian Peso (COP)', symbol: '$' },
  { code: 'PEN', name: 'Peruvian Sol (PEN)', symbol: 'S/.' },
  { code: 'ARS', name: 'Argentine Peso (ARS)', symbol: '$' },
  { code: 'UAH', name: 'Ukrainian Hryvnia (UAH)', symbol: '₴' },
  { code: 'KZT', name: 'Kazakhstani Tenge (KZT)', symbol: '₸' },
  { code: 'NGN', name: 'Nigerian Naira (NGN)', symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling (KES)', symbol: 'KSh' },
  { code: 'GHS', name: 'Ghanaian Cedi (GHS)', symbol: 'GH₵' },
  { code: 'TZS', name: 'Tanzanian Shilling (TZS)', symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling (UGX)', symbol: 'USh' },
  { code: 'MAD', name: 'Moroccan Dirham (MAD)', symbol: 'DH' },
  { code: 'DZD', name: 'Algerian Dinar (DZD)', symbol: 'DA' },
  { code: 'TND', name: 'Tunisian Dinar (TND)', symbol: 'DT' },
];

// ============================================================
// EXCHANGE RATES (relative to USD = 1.0)
// ============================================================
// Used to convert amounts between currencies on the dashboard.
// Example: 100 AED → USD = 100 / 3.6725 = ~27.22 USD
// ============================================================
export const EXCHANGE_RATES = {
  USD: 1.0,
  AED: 3.6725,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 155.0,
  CAD: 1.36,
  AUD: 1.50,
  LKR: 300.0,
  INR: 83.3,
  CHF: 0.90,
  CNY: 7.23,
  SGD: 1.35,
  NZD: 1.63,
  HKD: 7.80,
  ZAR: 18.2,
  SEK: 10.7,
  NOK: 10.8,
  DKK: 6.9,
  RUB: 91.0,
  KRW: 1350.0,
  TRY: 32.2,
  BRL: 5.15,
  MXN: 16.8,
  SAR: 3.75,
  QAR: 3.64,
  OMR: 0.385,
  BHD: 0.376,
  KWD: 0.307,
  MYR: 4.70,
  IDR: 16000.0,
  PHP: 57.5,
  THB: 36.5,
  VND: 25400.0,
  PKR: 278.0,
  BDT: 117.0,
  NPR: 133.0,
  EGP: 47.0,
  ILS: 3.70,
  PLN: 3.95,
  HUF: 355.0,
  CZK: 22.8,
  RON: 4.60,
  CLP: 920.0,
  COP: 3900.0,
  PEN: 3.72,
  ARS: 880.0,
  UAH: 39.5,
  KZT: 440.0,
  NGN: 1450.0,
  KES: 130.0,
  GHS: 14.5,
  TZS: 2600.0,
  UGX: 3800.0,
  MAD: 10.0,
  DZD: 134.0,
  TND: 3.12,
};
